import {createSlice} from "@reduxjs/toolkit";
import {createProduct,getAllProducts,updateProduct,deleteProduct,getSellerAllProducts,getOneProduct} from "../../../index"
const initialState={
    loading:false,
    error:null,
    product:{},
    products:[],
    sellerProducts:[],
    venderId:"",
    totalProducts:0
}
const productSlice=createSlice({
    name:"product",
    initialState,
    reducers:{},
    extraReducers:(builder)=>{
        builder.
        addCase(createProduct.pending,(state)=>{
            state.loading=true;
            state.error=null
        }).
        addCase(createProduct.fulfilled,(state,action)=>{
            state.products=[action.payload,...state.products]
        }).
        addCase(createProduct.rejected,(state,action)=>{
            state.loading=false;
            state.error=action.error.message
        }).
        addCase(getOneProduct.pending,(state)=>{
            state.loading=true;
            state.error=null
        }).
        addCase(getOneProduct.fulfilled,(state,action)=>{
            state.loading=false;
            state.product=action.payload
        }). 
        addCase(getOneProduct.rejected,(state,action)=>{
            state.loading=false;
            state.error=action.error.message
        }).
        addCase(getAllProducts.pending,(state)=>{
            state.loading=true;
            state.error=null
        }).
        addCase(getAllProducts.fulfilled,(state,action)=>{
            state.products=action.payload.data,
            state.totalProducts=action.payload.totalCount
        }). 
        addCase(getAllProducts.rejected,(state,action)=>{
            state.loading=false;
            state.error=action.error.message
        }).
        addCase(updateProduct.pending,(state)=>{
            state.loading=true;
            state.error=null
        }).
        addCase(updateProduct.fulfilled,(state,action)=>{
            state.products=[action.payload,...state.products.filter((product)=>product._id!==action.payload._id)]
        }). 
        addCase(updateProduct.rejected,(state,action)=>{
            state.loading=false;
            state.error=action.error.message
        }).
        addCase(deleteProduct.pending,(state)=>{
            state.loading=true;
            state.error=null
        }).
        addCase(deleteProduct.fulfilled,(state,action)=>{
            state.loading=false;
            state.products=state.products.filter((product)=>product._id!==action.payload._id)
        }).
        addCase(deleteProduct.rejected,(state,action)=>{
            state.loading=false;
            state.error=action.error.message
        })
        .addCase(getSellerAllProducts.pending,(state)=>{
            state.loading=true;
            state.error=null
        }).
        addCase(getSellerAllProducts.fulfilled,(state,action)=>{
            state.sellerProducts=action.payload.products;
            state.venderId=action.payload.sellerId
            state.loading=false
        }). 
        addCase(getSellerAllProducts.rejected,(state,action)=>{
            state.loading=false;
            state.error=action.error.message
        })

    }
})
export default productSlice.reducer