import {createSlice} from "@reduxjs/toolkit"
import {createOrder,getOrders,requestOrderRefund,cancelProducts,cancelOrderRefund,trackOrder,deliveredOrder,updateItemStatus,updateOderStatus, requestRefund} from "../../../index"
const initialState={
    loading:false,
    error:null,
    orders:[],
    totalOrders:0,
    trackedOrder:null,
    deliveredOrder:[],
    latestOrder:null
}
const orderSlice=createSlice({
    name:"order",
    initialState,
    reducers:{
        clearOrders(state){
            state.orders=[]
        }
    },
    extraReducers:(builder)=>{
        builder
        .addCase(createOrder.pending,(state)=>{
            state.loading=true,
            state.error=null
        })
        .addCase(createOrder.fulfilled,(state,action)=>{
            state.loading=false,
            state.orders=[action.payload,...state.orders],
            state.latestOrder=true
        })
        .addCase(createOrder.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(getOrders.pending,(state)=>{
            state.loading=true,
            state.error=null
        })
        .addCase(getOrders.fulfilled,(state,action)=>{
            state.loading=false,
            state.orders=action.payload.data
            state.totalOrders=action.payload.totalCount
        })
        .addCase(getOrders.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(trackOrder.pending,(state)=>{
            state.loading=true,
            state.error=null
        })
        .addCase(trackOrder.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(trackOrder.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(deliveredOrder.pending,(state)=>{
            state.loading=true,
            state.error=null
        })
        .addCase(deliveredOrder.fulfilled,(state,action)=>{
            state.loading=false,
            state.deliveredOrder=action?.payload
        })
        .addCase(deliveredOrder.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(updateItemStatus.pending,(state)=>{
            state.loading=true,
            state.error=null
        })
        .addCase(updateItemStatus.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(updateItemStatus.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(updateOderStatus.pending,(state)=>{
            state.loading=true,
            state.error=null
        })
        .addCase(updateOderStatus.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(updateOderStatus.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(requestOrderRefund.pending,(state)=>{
            state.loading=true,
            state.error=null    
        })
        .addCase(requestOrderRefund.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(requestOrderRefund.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(cancelOrderRefund.pending,(state)=>{
            state.loading=true,
            state.error=null    
        })
        .addCase(cancelOrderRefund.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(cancelOrderRefund.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(cancelProducts.pending,(state)=>{
            state.loading=true,
            state.error=null    
        })
        .addCase(cancelProducts.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(cancelProducts.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        .addCase(requestRefund.pending,(state)=>{
            state.loading=true,
            state.error=null    
        })
        .addCase(requestRefund.fulfilled,(state,action)=>{
            state.loading=false,
            state.trackedOrder=action?.payload
        })
        .addCase(requestRefund.rejected,(state,action)=>{
            state.loading=false,
            state.error=action.error.message
        })
        
    }
})
export const {clearOrders}=orderSlice.actions
export default orderSlice.reducer